name: Release Docker Image

on:
  workflow_run:
    workflows: [Run Integration Tests]
    branches:
      - main
    types:
      - completed

jobs:
  push_to_registry:
    name: Build & Push image to DockerHub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: github_tag_action
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Make release tags
        id: make_release_tags
        run: |
          raw_tag=${{ steps.github_tag_action.outputs.new_tag  }}
          tag=${raw_tag:1}
          image_name=${{ secrets.DOCKER_USERNAME }}/${PWD##*/}
          tags=$image_name:latest,$image_name:$tag
          echo "tags=$tags" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.make_release_tags.outputs.tags }}
